on:
  push:
    tags:
      - "*"
name: Publish Package
jobs:
  pack-solution:
    name: Pack solution
    permissions:
      contents: read
      packages: write
      releases: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pack solution
        uses: microsoft/powerplatform-actions/pack-solution@v0
        with:
          solution-file: Publisher.zip
          solution-folder: solution
      - name: Create release
        uses: softprops/action-gh-release@v1
      - name: Publish package
        run: npm publish
